name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Use Node.js v16.11.0
        uses: actions/setup-node@v1
        with:
          node-version: v16.11.0
      - name: Cache node modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('package-lock.json') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run test coverage
        run: npm run test:cov

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v2
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info
  checks:
    runs-on: ubuntu-latest
    needs: base_branch_cov
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.11.0
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.11.0
      - name: Cache node modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('package-lock.json') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run test coverage
        run: npm run test:cov

      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v0.6.1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: './coverage/lcov.info'
          base-lcov-file: './lcov.info'
          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: 'warning' # Possible options warning|error